Handle update for project
stakater/jira-service-desk-operator pull request #12
Opened 2020-08-19 12:33 UTC by H177

WIP: Handle update for project

2020-08-19 13:48 UTC, ahmedwaleedmalik commented on pkg/jiraservicedesk/client/client_project.go
> +		err := errors.New("Rest request to create Project failed with status " + strconv.Itoa(response.StatusCode) +
`Rest request to update Project`

2020-08-20 07:39 UTC, ahmedwaleedmalik commented on pkg/jiraservicedesk/client/client_project.go
> +	fmt.Println(updatedProject)
Remove this line

2020-08-20 07:41 UTC, ahmedwaleedmalik commented on controllers/project_controller.go
> +				return r.handleUpdate(req, project, instance)
rename project to `existingProject`

2020-08-20 07:42 UTC, ahmedwaleedmalik requested changes
Run `make verify` and ensure that there are no errors

2020-08-25 07:25 UTC, ahmedwaleedmalik requested changes

2020-08-25 07:25 UTC, ahmedwaleedmalik commented on api/v1alpha1/project_types.go
> +	errorMsg string = " is an immutable field, can't be changed while updating"
Variable name needs to be more specific, something like errorImmutableFieldMsg

2020-08-25 07:25 UTC, ahmedwaleedmalik commented on api/v1alpha1/project_types.go
> +	errorMsg string = " is an immutable field, can't be changed while updating"
Remove starting space you have already taken care of the formatting at `fmt.Errorf("%s %s", "ProjectTemplateKey", errorMsg)`

2020-08-25 07:25 UTC, ahmedwaleedmalik commented on api/v1alpha1/project_webhook.go
> +	"github.com/prometheus/common/log"
This is an invalid import for log. Use `logf` for logging instead

2020-08-25 07:25 UTC, ahmedwaleedmalik commented on api/v1alpha1/project_webhook.go
> +		log.Error(ok, "Error in finding the requested project")
This should return an error, don't just log it. Something like this should do
`return fmt.Errorf("Error casting old runtime object to %T from %T", oldProject, old)`

2020-08-25 07:25 UTC, ahmedwaleedmalik commented on pkg/jiraservicedesk/client/client_project.go
>  	// Add logic for updating project here
You can remove this comment now since we have implemented this

2020-08-25 07:25 UTC, ahmedwaleedmalik commented on pkg/jiraservicedesk/client/client_project_mappers.go
> +		PermissionScheme:    project.Spec.PermissionScheme,
Good catch here :D

2020-08-25 12:42 UTC, stakater-user commented
@ahmedwaleedmalik Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater/jira-service-desk-operator:SNAPSHOT-PR-12-dac3814b`

2020-08-26 08:50 UTC, stakater-user commented
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-12-37e98ab2`

2020-08-27 07:37 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-12-01170406`

2020-08-28 07:48 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-12-d7dfb411`

2020-08-28 07:52 UTC, ahmedwaleedmalik approved these changes
LGTM!

2020-08-28 07:53 UTC, merged