WIP: Handle customer tests
stakater/jira-service-desk-operator pull request #36
Opened 2020-09-24 09:10 UTC by rehanjaved237

2020-09-24 09:20 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-36-dac7da5a`

2020-09-24 12:33 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-36-c74192b9`

2020-09-24 12:40 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-36-7d61cbd4`

2020-09-29 07:41 UTC, ahmedwaleedmalik requested changes

2020-09-29 07:41 UTC, ahmedwaleedmalik commented on controllers/project_controller_test.go
> +			util.TryDeleteProject(projectInvalidInput.Spec.Name, ns)
Why are we trying to delete `projectInvalidInput.Spec.Name` in afterEach block ?

2020-09-29 07:41 UTC, ahmedwaleedmalik commented on controllers/customer_controller_test.go
> +
Ideally this should have a `beforeAll` block to create a project and `afterAll` block to delete that project

2020-09-29 07:41 UTC, ahmedwaleedmalik commented on controllers/project_controller.go
> +
Remove this redundant newline

2020-09-29 07:41 UTC, ahmedwaleedmalik commented on pkg/jiraservicedesk/client/client_customer.go
> +	fmt.Println("Check1")
Remove this log

2020-09-29 07:41 UTC, ahmedwaleedmalik commented on pkg/jiraservicedesk/client/client_customer.go
> +	"fmt"
Remove this import

2020-09-29 07:41 UTC, ahmedwaleedmalik commented on pkg/jiraservicedesk/client/client_project_test.go
> +	st.Reject(t, err, nil)
Please use `Expect` instead of `Reject` as discussed

2020-09-29 10:19 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-36-b72cdc82`

2020-09-29 10:21 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-36-f0b9af78`

2020-09-29 10:58 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-36-c26c4d6f`

2020-09-29 11:23 UTC, ahmedwaleedmalik approved these changes
LGTM

2020-09-29 11:25 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-36-136fd1bc`

2020-09-29 11:27 UTC, merged