WIP: Add implementation for legacy customer
stakater/jira-service-desk-operator pull request #58
Opened 2021-01-18 07:43 UTC by rehanjaved237

2021-01-18 07:45 UTC, stakater-user commented
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/fe5d4f55bd8cba5ee9be3e6b6310577edf8ca263/checks) has Failed!

2021-01-18 08:04 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-58-bd586141`

2021-01-18 10:23 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-58-8aff361d`

2021-01-18 11:55 UTC, stakater-user commented
@rehanjaved237 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater/jira-service-desk-operator/commit/1395ae1e2adea37ff36b0349b3c61a0eef2b95ee/checks) has Failed!

2021-01-18 17:14 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-58-7509f5a2`

2021-01-19 07:38 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-58-b8e3c201`

2021-01-19 08:26 UTC, stakater-user commented
@rehanjaved237 Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-58-bfc659ba`

2021-01-19 09:11 UTC, ahmedwaleedmalik requested changes
Please add documentation for `LegacyCustomer` in the readme of the project.

2021-01-19 09:11 UTC, ahmedwaleedmalik commented on api/v1alpha1/customer_types.go
> +		}
It takes a few seconds for customers to be persisted at JSD. Check if it's pending with known values are return.
```suggestion
		// It takes a few seconds for customers to be persisted at JSD. Check if it's pending with known values are return.
		if existingCustomer.Spec.Name == "User " && existingCustomer.Spec.Email == "?" {
			return true, nil
		}
```

2021-01-21 05:40 UTC, ahmedwaleedmalik approved these changes
LGTM

2021-01-21 05:41 UTC, merged

2021-01-21 05:45 UTC, stakater-user commented
@ahmedwaleedmalik Image is available for testing. `docker pull stakater/jira-service-desk-operator:SNAPSHOT-PR-58-209c2a65`